### ISSUE TITLE
Test failing at lib-datahandler

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#765]
On the vagrant (the new one) deployment, a test consistently fails (as wells on machos)

```
default: Running org.eclipse.sw360.datahandler.couchdb.AttachmentContentDownloaderTest
    default: Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.145 sec <<< FAILURE! - in org.eclipse.sw360.datahandler.couchdb.AttachmentContentDownloaderTest
    default: testABlackHoleUrl(org.eclipse.sw360.datahandler.couchdb.AttachmentContentDownloaderTest)  Time elapsed: 0.007 sec  <<< FAILURE!
    default: java.lang.AssertionError: 
    default: Expected: a string containing "test"
    default:      but: was "sw360db"
    default: 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    default: 	at org.junit.Assert.assertThat(Assert.java:956)
    default: 	at org.junit.Assert.assertThat(Assert.java:923)
    default: 	at org.eclipse.sw360.datahandler.TestUtils.assertTestString(TestUtils.java:78)
    default: 	at org.eclipse.sw360.datahandler.TestUtils.assertTestDbNames(TestUtils.java:66)
    default: 	at org.eclipse.sw360.datahandler.TestUtils.<clinit>(TestUtils.java:61)
    default: 	at org.eclipse.sw360.datahandler.couchdb.AttachmentContentDownloaderTest.testABlackHoleUrl(AttachmentContentDownloaderTest.java:67)
    default: 
    default: testTheCouchDbUrl(org.eclipse.sw360.datahandler.couchdb.AttachmentContentDownloaderTest)  Time elapsed: 0.135 sec  <<< ERROR!
    default: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.sw360.datahandler.TestUtils
    default: 	at org.eclipse.sw360.datahandler.couchdb.AttachmentContentDownloaderTest.testTheCouchDbUrl(AttachmentContentDownloaderTest.java:60)
    default: 
    default: Running org.eclipse.sw360.datahandler.couchdb.AttachmentStreamConnectorTest
    default: Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.132 sec - in org.eclipse.sw360.datahandler.couchdb.AttachmentStreamConnectorTest
    default: Running org.eclipse.sw360.datahandler.couchdb.DatabaseConnectorTest
    default: Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.611 sec - in org.eclipse.sw360.datahandler.couchdb.DatabaseConnectorTest
    default: Running org.eclipse.sw360.datahandler.couchdb.AttachmentContentWrapperTest
    default: Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in org.eclipse.sw360.datahandler.couchdb.AttachmentContentWrapperTest
    default: Running org.eclipse.sw360.datahandler.couchdb.AttachmentConnectorTest
    default: Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec - in org.eclipse.sw360.datahandler.couchdb.AttachmentConnectorTest
    default: Running org.eclipse.sw360.datahandler.resourcelists.ResourceListControllerTest
    default: Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec - in org.eclipse.sw360.datahandler.resourcelists.ResourceListControllerTest
    default: Running org.eclipse.sw360.datahandler.resourcelists.ResourceComparatorGeneratorTest
    default: Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.eclipse.sw360.datahandler.resourcelists.ResourceComparatorGeneratorTest
    default: Running org.eclipse.sw360.datahandler.resourcelists.PaginationOptionsTest
    default: Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in org.eclipse.sw360.datahandler.resourcelists.PaginationOptionsTest
    default: Running org.eclipse.sw360.datahandler.resourcelists.PaginationResultTest
    default: Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.eclipse.sw360.datahandler.resourcelists.PaginationResultTest
    default: 
    default: Results :
    default: 
    default: Failed tests: 
    default:   AttachmentContentDownloaderTest.testABlackHoleUrl:67 
    default: Expected: a string containing "test"
    default:      but: was "sw360db"
    default: 
    default: Tests in error: 
    default:   AttachmentContentDownloaderTest.testTheCouchDbUrl:60 NoClassDefFound Could not...
    default: 
    default: Tests run: 185, Failures: 1, Errors: 1, Skipped: 0
    default: [INFO] ------------------------------------------------------------------------
    default: [INFO] Reactor Summary:
    default: [INFO] 
    default: [INFO] build-configuration ................................ SUCCESS [ 25.731 s]
    default: [INFO] datahandler ........................................ FAILURE [ 37.505 s]
    default: [INFO] commonIO ........................................... SKIPPED
    default: [INFO] exporters .......................................... SKIPPED
```
